Enable repo deletion when there are no snapshots
NetApp/restic pull request #9
Opened 2021-09-28 22:01 UTC by raghu-sarangapani

Enable repo deletion when there are no snapshots
- Upon deleting a snapshot, the forget code checks to see if there are more snapshots available. If there are no snapshots, the forget code will call the backend's Delete function which cleans up all the restic files. Empty folders automatically get removed

Tested out the change with SG

2021-09-28 23:41 UTC, coffeefreak101 requested changes

2021-09-28 23:41 UTC, coffeefreak101 commented on cmd/restic/cmd_forget.go
> +	f.BoolVar(&forgetOptions.skipRepoDelete, "skip-repo-delete", false, "skip deleting the repo if there are no more snapshots")
The flag should probably be something more like "delete-empty-repo" to convey to the user that restic will also remove the repo if it is now empty.
The flag should be "false" by default. The user should have to explicitly set the flag to enable it. That way, we don't introduce any unexpected behavior to previous tests or scripts. Similar to maintaining backwards compatibility.

2021-09-28 23:41 UTC, coffeefreak101 commented on cmd/restic/cmd_forget.go
> +		remainingSnapshots := len(allSnapshots)
nit: Instead of collecting all the snapshots and doing a `len()`, you could just have a `snapshotCount` and see if it is greater than 1.
ex:
```
var snapshotCount int
for _ = range FindFilteredSnapshots(ctx, repo, opts.Hosts, opts.Tags, opts.Paths, []string{}) {
    snapshotCount++
}
```

2021-09-29 18:24 UTC, raghu-sarangapani commented on cmd/restic/cmd_forget.go
> +		remainingSnapshots := len(allSnapshots)
Fixed

2021-09-29 18:24 UTC, raghu-sarangapani commented on cmd/restic/cmd_forget.go
> +	f.BoolVar(&forgetOptions.skipRepoDelete, "skip-repo-delete", false, "skip deleting the repo if there are no more snapshots")
Fixed

2021-09-29 19:37 UTC, coffeefreak101 commented on cmd/restic/cmd_forget.go
> +	f.BoolVar(&forgetOptions.deleteEmptyRepo, "delete-empty-repo", false, "skip deleting the repo if there are no more snapshots")
Probably should update the help message to say something like "Delete the repo if there are no more snapshots".

2021-09-29 19:41 UTC, raghu-sarangapani commented on cmd/restic/cmd_forget.go
> +	f.BoolVar(&forgetOptions.deleteEmptyRepo, "delete-empty-repo", false, "skip deleting the repo if there are no more snapshots")
Fixed

2021-09-29 19:46 UTC, coffeefreak101 approved these changes

2021-09-29 20:33 UTC, merged